-- Wires up the plans/plan_exercises tables (defined in exercise_schema.sql but
-- unused until now) so a built plan is persisted per-user in Postgres instead
-- of living only in the in-process Memory.finished_plan singleton.
--
-- Run with: psql -d exercise_database -f migrations/001_plan_persistence.sql

-- plan_exercises: add day, and fix the PK. The old PK (plan_id, exercise_id)
-- can't store a compound lift (squat/bench/deadlift) on two different days in
-- the same week even though PLAN_PROMPT explicitly allows that — a plain
-- serial PK removes the false uniqueness constraint.
ALTER TABLE plan_exercises ADD COLUMN day varchar(9) NOT NULL DEFAULT 'monday';
ALTER TABLE plan_exercises ALTER COLUMN day DROP DEFAULT;  -- default only satisfied NOT NULL on add; table is empty
ALTER TABLE plan_exercises DROP CONSTRAINT plan_exercises_pkey;
ALTER TABLE plan_exercises ADD COLUMN plan_exercise_id serial PRIMARY KEY;

-- plans: one active plan per user — building a new plan replaces the old one,
-- matching today's Memory.finished_plan-is-a-singleton behaviour. plan_id was
-- a plain integer PK (see evaluation/seed_user.sql's comment on injuries for
-- the same pattern); make it auto-generated now that Python inserts rows.
ALTER TABLE plans ALTER COLUMN plan_id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE plans ADD CONSTRAINT plans_user_id_key UNIQUE (user_id);
