-- ReFit database schema. Run once against an empty database:
--   createdb exercise_database
--   psql -d exercise_database -f db/schema.sql
--   psql -d exercise_database -f db/seed_users.sql

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE "user" (
  "user_id" integer PRIMARY KEY,
  "username" varchar(255) UNIQUE NOT NULL,
  "full_name" varchar(255) NOT NULL,
  "email" varchar(255) NOT NULL,
  "gender" varchar(1) NOT NULL,
  "date_of_birth" date,
  "date_joined" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "exercises" (
  "exercise_id" integer PRIMARY KEY,
  "exercise_name" varchar(100),
  "description" text,
  "type" varchar(20),
  "difficulty" varchar(6) NOT NULL,
  "equipment" varchar(20) NOT NULL,
  "embedding" vector(768)                      -- nomic-embed-text
);

CREATE TABLE "muscles" (
  "muscle_id" integer PRIMARY KEY,
  "muscle_name" varchar(100) NOT NULL
);

CREATE TABLE "muscles_exercised" (
  "exercise_id" integer,
  "muscle_id" integer,
  "role" varchar(10) NOT NULL,
  PRIMARY KEY ("exercise_id", "muscle_id")
);

CREATE TABLE "injuries" (
  "injury_id" integer PRIMARY KEY,
  "user_id" integer,
  "location" varchar(20),
  "severity" varchar(6),
  "occurance" timestamp DEFAULT (now()),
  "status" varchar(20)
);

-- One active plan per user: building a new plan replaces the old one, matching
-- the Memory.finished_plan-is-a-singleton behaviour on the Python side.
CREATE TABLE "plans" (
  "plan_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "plan_name" varchar(255),
  "user_id" integer UNIQUE
);

-- The PK is a plain serial rather than (plan_id, exercise_id): a compound lift
-- (squat/bench/deadlift) can appear on two different days of the same week,
-- which PLAN_PROMPT explicitly allows, so that pair is not unique.
CREATE TABLE "plan_exercises" (
  "plan_exercise_id" serial PRIMARY KEY,
  "plan_id" integer NOT NULL,
  "exercise_id" integer NOT NULL,
  "day" varchar(9) NOT NULL,
  "order" integer,
  "sets" integer,
  "reps" integer
);

-- Per-user override of an exercise's difficulty. The global
-- exercises.difficulty is the shared default; a row here wins for that user,
-- letting people re-rate exercises they personally find easier or harder.
-- NOT IMPLEMENTED, FUTURE WORK!
CREATE TABLE "user_exercise_difficulty" (
  "user_id" integer,
  "exercise_id" integer,
  "difficulty" varchar(6) NOT NULL,   -- Easy | Medium | Hard
  PRIMARY KEY ("user_id", "exercise_id")
);

-- Nutrition reference data: CoFID 2021 (McCance & Widdowson's Composition of Foods).
-- All values are per 100g of food, except alcoholic beverages which are per 100ml.
CREATE TABLE "foods" (
  "id"             serial PRIMARY KEY,
  "food_code"      varchar(10) NOT NULL,      
  "food_name"      varchar(255) NOT NULL,
  "description"    text,
  "food_group"     varchar(4),                
  "kcal"           real,
  "protein_g"      real,
  "fat_g"          real,
  "carb_g"         real,
  "total_sugars_g" real,
  "fibre_nsp_g"    real,                       
  "fibre_aoac_g"   real,                       
  "embedding"      vector(768)                 -- nomic-embed-text
);
CREATE INDEX ON "foods" ("food_code");


CREATE TABLE "nutrient_reference" (
  "id"         serial PRIMARY KEY,
  "sex"        varchar(1) NOT NULL,       -- 'M' / 'F' 
  "age_min"    integer NOT NULL,
  "age_max"    integer NOT NULL,          -- 200 = open-ended (75+)
  "nutrient"   varchar(20) NOT NULL,      -- energy_kcal, protein_g, fat_g, satfat_g, carb_g, free_sugars_g, fibre_g
  "value"      real NOT NULL,
  "limit_type" varchar(6) NOT NULL        -- 'target' | 'min' (at least) | 'max' (less than)
);
CREATE INDEX ON "nutrient_reference" ("sex", "age_min", "age_max");

-- The food diary stores food_id + grams rather than denormalised macros, keeping
-- "foods" the single source of truth: get_food_macros already scales the per-100g
-- figures by weight, so the diary reuses that path instead of copying numbers.
-- Trade-off: a CoFID correction retroactively alters logged history, which is the
-- right behaviour here (the food did not change, the measurement did).
--
-- logged_on is a real column rather than logged_at::date so an entry can be
-- backdated ("I ate this yesterday") without timezone arithmetic.
CREATE TABLE "food_log" (
  "log_id"    bigserial PRIMARY KEY,
  "user_id"   integer   NOT NULL REFERENCES "user"("user_id"),
  "food_id"   integer   NOT NULL REFERENCES "foods"("id"),
  "grams"     real      NOT NULL CHECK ("grams" > 0),
  "logged_on" date      NOT NULL DEFAULT CURRENT_DATE,
  "logged_at" timestamp NOT NULL DEFAULT now()
);
CREATE INDEX ON "food_log" ("user_id", "logged_on");

-- Goal-adjusted targets that override the PHE population guideline. Columns
-- deliberately mirror nutrient_reference's, so layering a user's overrides over
-- the population defaults is a plain dict update in retrieval.effective_targets.
-- Nothing writes this table yet: the daily goal is currently the PHE baseline
-- for the user's sex and age.
CREATE TABLE "user_nutrition_targets" (
  "user_id"    integer     NOT NULL REFERENCES "user"("user_id"),
  "nutrient"   varchar(20) NOT NULL,
  "value"      real        NOT NULL,
  "limit_type" varchar(6)  NOT NULL,
  PRIMARY KEY ("user_id", "nutrient")
);

CREATE TABLE "user_profile" (
  "user_id"    integer PRIMARY KEY REFERENCES "user" ("user_id"),
  "profile"    jsonb NOT NULL DEFAULT '{}'::jsonb,
  "updated_at" timestamp NOT NULL DEFAULT now()
);

COMMENT ON COLUMN "exercises"."description" IS 'Description of the exercise';

COMMENT ON COLUMN "user_profile"."profile" IS
  'Slots: conditions, medications, injuries, goals, equipment, constraints, other. '
  'Merged from conversation each turn; never overwritten wholesale. '
  'Contains health data — belongs inside the field-level encryption scope.';

ALTER TABLE "muscles_exercised" ADD FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("exercise_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "muscles_exercised" ADD FOREIGN KEY ("muscle_id") REFERENCES "muscles" ("muscle_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "injuries" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "plan_exercises" ADD FOREIGN KEY ("plan_id") REFERENCES "plans" ("plan_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "plan_exercises" ADD FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("exercise_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "plans" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_exercise_difficulty" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_exercise_difficulty" ADD FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("exercise_id") DEFERRABLE INITIALLY IMMEDIATE;
